-- таблица пользователей
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(200) NOT NULL UNIQUE,
    login VARCHAR(200) NOT NULL UNIQUE,
    name VARCHAR(50),
    birthday DATE
);

-- таблица рейтингов фильма
CREATE TABLE IF NOT EXISTS mpa(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(25)
);

-- таблица фильмов
CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50),
    description VARCHAR(200),
    release_date DATE,
    duration REAL,
    mpa_id INTEGER,
    FOREIGN KEY(mpa_id) REFERENCES mpa(id) ON DELETE CASCADE
);

-- таблица жанров
CREATE TABLE IF NOT EXISTS genres(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50)
);

-- таблица связи пользователь-друг
CREATE TABLE IF NOT EXISTS friendship(
    user_id INTEGER,
    friend_id INTEGER,
    PRIMARY KEY(user_id, friend_id),
    FOREIGN KEY(user_id) REFERENCES users(id),
    FOREIGN KEY(friend_id) REFERENCES users(id)
);

-- таблица связи лайков
CREATE TABLE IF NOT EXISTS likes(
    user_id INTEGER,
    film_id INTEGER,
    PRIMARY KEY(user_id, film_id),
    FOREIGN KEY(user_id) REFERENCES users(id),
    FOREIGN KEY(film_id) REFERENCES films(id)
);

-- таблица связи фильм-жанр
CREATE TABLE IF NOT EXISTS film_genre(
    genre_id INTEGER,
    film_id INTEGER,
    PRIMARY KEY(genre_id, film_id),
    FOREIGN KEY(genre_id) REFERENCES genres(id),
    FOREIGN KEY(film_id) REFERENCES films(id)
);